apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: talend-infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.8.1
    helm:
      releaseName: prometheus-operator
      values: |
        global:
          imagePullSecrets: 
            - name: "artifactory-docker-secret"
        
        commonLabels:
          # Tells prometheus-infra to scrape prometheus-operator
          prometheus: prometheus-infra
        
        prometheusOperator:
          enabled: true
          image:
            repository: prometheus-operator/prometheus-operator
            registry: ghcr.io/qlik-trial
            pullPolicy: IfNotPresent
            digest: sha256:e76d06ac84abeb466feb9682e1d0385c4e5a463bc023b32446916b640546a289
            tag: 'v0.70.0'
          prometheusConfigReloader:
            image:
              repository: prometheus-operator/prometheus-config-reloader
              registry: ghcr.io/qlik-trial
              pullPolicy: IfNotPresent
              digest: sha256:411cec4bc5e6306804c2d5939c165411a88fb7991c2bd0c3ef4866387f683374
              tag: 'v0.70.0'
          thanosImage:
            repository: thanos/thanos
            registry: ghcr.io/qlik-trial
            pullPolicy: IfNotPresent
            digest: sha256:70d2ea73792e2d26a6eb45e0c999fc88e8cebc1ba443ca059e19715231365cc8
            tag: 'v0.33.0' 
          logLevel: info
          logFormat: json
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 400m
              memory: 1Gi
        crds:
          enabled: false
        defaultRules:
          create: false
        prometheus-windows-exporter:
          prometheus:
            monitor:
              enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubernetesServiceMonitors:
          enabled: true
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        coreDns:
          enabled: false
        kubeDns:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true