apiVersion: v2
description: vector-agent wrapper chart
name: qlik-vector
version: 1.0.0
appVersion: 
home: 
sources:
  - https://github.com/qlik-trial/kube-prometheus-stack
dependencies:
  - name: vector
    alias: vector-agent
    version: 0.26.0
    repository: "https://helm.vector.dev"
    condition: vector-agent.enabled
  - name: vector
    alias: vector-infra
    version: 0.30.0
    repository: "https://helm.vector.dev"
    condition: vector-infra.enabled