---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-infra
roleRef:
  kind: ClusterRole
  name: vector-infra
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vector-infra
    namespace: logging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-infra
rules:
  - apiGroups: ['']
    resources: [configmaps]
    verbs: [get, watch, list]
