apiVersion: v2
description: kube-prometheus-stack wrapper chart
name: kube-prometheus-stack
version: 1.0.0
appVersion: 55.8.1
home: https://github.com/prometheus-operator/kube-prometheus
sources:
  - https://github.com/qlik-trial/kube-prometheus-stack
dependencies:
  - name: kube-prometheus-stack
    alias: kube-prometheus-stack
    version: 55.8.1
    repository: "https://prometheus-community.github.io/helm-charts"
