kube-prometheus-stack:
  prometheusOperator:
    enabled: false
  crds:
    enabled: false
  defaultRules:
    create: false
  prometheus-windows-exporter:
    prometheus:
      monitor:
        enabled: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubernetesServiceMonitors:
    enabled: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: false
postgresql:
  enabled: true
thanos:
  bucketweb:
    enabled: false
  compactor:
    enabled: false
  queryFrontend:
    enabled: false
  receive:
    enabled: false
  storegateway:
    enabled: false
